#!/bin/bash
set -e

PACKAGES=(
"agenticsjs"
"@ruv/sparc-ui"
"dspy.ts"
"@agentics.org/agentic-mcp"
"@agentics.org/sparc2"
"create-sparc"
"vscode-remote-mcp"
"claude-flow"
"qudag"
"ruv-swarm"
"cuda-wasm"
"flow-nexus"
"@ruvnet/bmssp"
"bmssp-wasm"
"sublinear-time-solver"
"temporal-lead-solver"
"temporal-neural-solver"
"psycho-symbolic-reasoner"
"consciousness-explorer"
"strange-loops"
"strange-loops-mcp"
"@ruvnet/strange-loop"
"goalie"
"agentic-payments"
"agentic-flow"
"agent-booster"
"agentdb"
"ruvi"
"lean-agentic"
"midstreamer"
"aidefence"
"aidefense"
"research-swarm"
"agentic-jujutsu"
"@qudag/cli"
"@qudag/mcp-sse"
"@qudag/mcp-stdio"
"@qudag/napi-core"
"@foxruv/nova-medicina"
"@neural-trader/core"
"@neural-trader/mcp-protocol"
"@neural-trader/backtesting"
"@neural-trader/brokers"
"@neural-trader/execution"
"@neural-trader/features"
"@neural-trader/market-data"
"@neural-trader/neural"
"@neural-trader/news-trading"
"@neural-trader/portfolio"
"@neural-trader/prediction-markets"
"@neural-trader/risk"
"@neural-trader/sports-betting"
"@neural-trader/strategies"
"@neural-trader/mcp"
"neural-trader"
"@neural-trader/benchoptimizer"
"@neural-trader/syndicate"
"@neural-trader/backend"
"@neural-trader/neuro-divergent"
"@neural-trader/predictor"
"@neural-trader/e2b-strategies"
"@agentic-robotics/linux-x64-gnu"
"@agentic-robotics/core"
"@agentic-robotics/cli"
"@agentic-robotics/mcp"
"agentic-robotics"
"@neural-trader/agentic-accounting-types"
"@neural-trader/agentic-accounting-rust-core"
"@neural-trader/agentic-accounting-core"
"@neural-trader/agentic-accounting-agents"
"@neural-trader/agentic-accounting-mcp"
"@neural-trader/agentic-accounting-cli"
"@agentic-robotics/self-learning"
"@neural-trader/example-portfolio-optimization"
"@neural-trader/example-market-microstructure"
"@neural-trader/example-energy-forecasting"
"@neural-trader/example-supply-chain-prediction"
"@neural-trader/example-logistics-optimization"
"@neural-trader/example-dynamic-pricing"
"@neural-trader/example-energy-grid-optimization"
"@neural-trader/example-healthcare-optimization"
"@neural-trader/example-quantum-optimization"
"@neural-trader/example-neuromorphic-computing"
"@neural-trader/example-evolutionary-game-theory"
"@foxruv/agent-learning-core"
"@foxruv/iris"
)

for pkg in "${PACKAGES[@]}"
do
  # Scoped packages result in tgz files like __scope__pkgname-version.tgz, so handle both formats
  PKG_BASENAME="${pkg/@/_}"  # Replace @ with _
  if ls "${PKG_BASENAME}-"*.tgz 1> /dev/null 2>&1; then
    echo "Already downloaded: $pkg"
  else
    echo "Downloading: $pkg"
    npm pack "$pkg"
  fi
done

echo "All npm package downloads complete! Only missing/new packages were downloaded."